export const currentUserMock = {
  avatar_url: "https://avatars.githubusercontent.com/u/63323085?v=4",
  bio: null,
  blog: "",
  company: null,
  created_at: "2020-04-07T23:08:55Z",
  email: null,
  events_url: "https://api.github.com/users/AndrelhVieira/events{/privacy}",
  exactMoment: "July 9th 2021, 10:48:35 am",
  followers: 4,
  followers_url: "https://api.github.com/users/AndrelhVieira/followers",
  following: 7,
  following_url:
    "https://api.github.com/users/AndrelhVieira/following{/other_user}",
  gists_url: "https://api.github.com/users/AndrelhVieira/gists{/gist_id}",
  gravatar_id: "",
  hireable: null,
  html_url: "https://github.com/AndrelhVieira",
  id: 63323085,
  location: null,
  login: "AndrelhVieira",
  momentsAgo: "a few seconds ago",
  name: "André Luiz Hiller Vieira",
  node_id: "MDQ6VXNlcjYzMzIzMDg1",
  organizations_url: "https://api.github.com/users/AndrelhVieira/orgs",
  public_gists: 0,
  public_repos: 10,
  received_events_url:
    "https://api.github.com/users/AndrelhVieira/received_events",
  repos_url: "https://api.github.com/users/AndrelhVieira/repos",
  site_admin: false,
  starred_url:
    "https://api.github.com/users/AndrelhVieira/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/AndrelhVieira/subscriptions",
  twitter_username: null,
  type: "User",
  updated_at: "2021-07-09T12:36:20Z",
  url: "https://api.github.com/users/AndrelhVieira",
};
